import assert from 'node:assert/strict';
import {CyberHud} from '../dist/cyber-hud.mjs';
const hud=new CyberHud();
const hand={id:'Left',tips:Array.from({length:5},(_,i)=>({x:200+i*20,y:300})),openness:1,angle:.25,pinch:false,closed:false};
hud.update([hand],0,1280,720);
assert.match(hud.lines[0].text,/track.acquire/);
hud.update([hand],200,1280,720);
assert.equal(hud.lines.length,1,'still hands do not generate fake activity');
hand.tips[1].x+=30;
hud.update([hand],400,1280,720);
assert.match(hud.lines.at(-1).text,/circuit.route\(1, 0.195, 0.417\)/);
hand.pinch=true;hud.update([hand],600,1280,720);
assert.match(hud.lines.at(-1).text,/field.bind/);
hand.pinch=false;hand.closed=true;hud.update([hand],800,1280,720);
assert.match(hud.lines.at(-1).text,/field.gather/);
hand.closed=false;hud.update([hand],1000,1280,720);
assert.equal(hud.lines.at(-1).text,'field.release();');
hud.update([],6500,1280,720);
assert.equal(hud.lines.length,0);assert.equal(hud.samples.size,0);
hud.update([hand],6700,1280,720);assert.match(hud.lines[0].text,/track.acquire/);
hud.reset();assert.equal(hud.sequence,0);assert.equal(hud.lines.length,0);
console.log('Cyber HUD: live coordinates, finger motion, idle, gesture transitions, loss/reacquisition, reset passed.');
hand.pinch=true;hud.updateVectors([hand],0,720);
const original=hud.anchors.get('Left');
hand.tips=hand.tips.map(p=>({x:p.x+90,y:p.y-40}));
hud.updateVectors([hand],120,720);
assert.equal(hud.anchors.get('Left'),original);assert.equal(original.end.x-original.start.x,90);
hand.pinch=false;hud.updateVectors([hand],240,720);
assert.equal(hud.anchors.get('Left'),original,'brief pinch loss retains anchor');
hand.pinch=true;hud.updateVectors([hand],320,720);
assert.equal(hud.anchors.get('Left'),original,'recovered pinch continues same vector');
hud.updateVectors([],500,720);assert.equal(hud.anchors.size,1,'brief hand loss retains vector');
hud.updateVectors([],600,720);assert.equal(hud.anchors.size,0);assert.equal(hud.releasedVectors.length,1);
hud.updateVectors([hand],700,720);assert.notEqual(hud.anchors.get('Left'),original,'new pinch starts new anchor');
hud.updateVectors([],2400,720);assert(!hud.releasedVectors.includes(original),'released vector expires');
hud.reset();assert.equal(hud.anchors.size,0);assert.equal(hud.releasedVectors.length,0);
console.log('Vector drag: stable anchor, pinch/hand dropout tolerance, release, restart and expiry passed.');
// A normal short drag must render a cluster, not one sparse fragment.
function fragmentCount(length,u=1){
  const labels=[];
  const paint=new Proxy({globalAlpha:1,fillText:text=>{if(paint.globalAlpha>.25)labels.push(text)}},{get:(target,key)=>key in target?target[key]:()=>{}});
  const v={path:[{x:300,y:300}],end:{x:300+length*u,y:300},speed:0};
  hud.drawDataStream(paint,v,1000,u,1);labels.length=0;hud.drawDataStream(paint,v,1500,u,1);
  return labels.filter(text=>!text.startsWith('op.')).length;
}
assert.equal(fragmentCount(40),3);
assert.equal(fragmentCount(40,1.5),3);
assert(fragmentCount(200)>=4);
assert(fragmentCount(1000)<=18);
assert.equal(fragmentCount(4),0);
console.log('Fragment density: short/long pulls, Full HD scaling and count cap passed.');

const pairPaint=new Proxy({},{get:()=>()=>{}});
hud.reset();hud.anchors.set('Left',{end:{x:100,y:200}});hud.anchors.set('Right',{end:{x:400,y:200}});
hud.drawPairNetwork(pairPaint,0,1,['cyan']);hud.drawPairNetwork(pairPaint,100,1,['cyan']);
assert(hud.pair.alpha>0);assert.equal(hud.pair.span,300);
hud.anchors.get('Right').end={x:600,y:400};hud.drawPairNetwork(pairPaint,200,1,['cyan']);
assert(hud.pair.span>300);assert(hud.pair.angle>0);
hud.anchors.clear();for(let t=300;t<2500;t+=100)hud.drawPairNetwork(pairPaint,t,1,['cyan']);
assert.equal(hud.pair,null);hud.reset();assert.equal(hud.pair,null);
console.log('Pair network: opening, stretching, rotation, release fade and reset passed.');
